// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVKwwoOeXrqu9ycVrT0TUYqsFNHvoZUI',
    appId: '1:291799346164:web:b9e3af5feee846bd19a7a1',
    messagingSenderId: '291799346164',
    projectId: 'plant-nursery-app-c39bb',
    authDomain: 'plant-nursery-app-c39bb.firebaseapp.com',
    storageBucket: 'plant-nursery-app-c39bb.firebasestorage.app',
    measurementId: 'G-NN5FZ7S809',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtAtgPZaaWkrb4EWM2FlzoGKs1d--3dis',
    appId: '1:291799346164:android:a794908d9740a20319a7a1',
    messagingSenderId: '291799346164',
    projectId: 'plant-nursery-app-c39bb',
    storageBucket: 'plant-nursery-app-c39bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgB9VJX0aqeyq4j0zF0gR1jiPVu1WrgyI',
    appId: '1:291799346164:ios:67ce8d69eba7177219a7a1',
    messagingSenderId: '291799346164',
    projectId: 'plant-nursery-app-c39bb',
    storageBucket: 'plant-nursery-app-c39bb.firebasestorage.app',
    iosBundleId: 'com.example.plantNuseryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgB9VJX0aqeyq4j0zF0gR1jiPVu1WrgyI',
    appId: '1:291799346164:ios:67ce8d69eba7177219a7a1',
    messagingSenderId: '291799346164',
    projectId: 'plant-nursery-app-c39bb',
    storageBucket: 'plant-nursery-app-c39bb.firebasestorage.app',
    iosBundleId: 'com.example.plantNuseryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTVKwwoOeXrqu9ycVrT0TUYqsFNHvoZUI',
    appId: '1:291799346164:web:b2a66fb8112522a219a7a1',
    messagingSenderId: '291799346164',
    projectId: 'plant-nursery-app-c39bb',
    authDomain: 'plant-nursery-app-c39bb.firebaseapp.com',
    storageBucket: 'plant-nursery-app-c39bb.firebasestorage.app',
    measurementId: 'G-96LYBFDQ63',
  );
}
